---

  - name: Install dnf-automatic
    dnf:
      name: dnf-automatic
      state: installed
      #update_cache: yes

  - name: Enable dnf-automatic
    service:
      name: dnf-automatic.timer
      state: started
      enabled: true
